services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: picpay-postgres
    env_file:
      - ./env/.env
    environment:
      - POSTGRES_DB=picpay
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data: